### ISSUE TITLE
Not able to get the list

### ISSUE THREAD

**Issue by Sharathnasa** [jmrezayi2/Applist#2]
Hello,
I would like to thank you, for writing such an excellent plugin. The plugin is not fetching any details. I'm using this plugin for Cordova application. 
I'm getting the below exception:
"Uncaught TypeError: undefined is not a function", source: file:///android_asset/www/plugins/org.jmrezayi2.Applist/www/Applist.js (12)

Im following the steps which you have mentioned in the usage section. Am'I doing anything fishy?? If soo, could you please help me in this regard. I would be great if you reply asap.

Thanks and Regards,
Sharath

**Comment by Sharathnasa** [comment]
Hello,
I was able to get rid of the above error, by removing "startDate","endDate" paramter from AppList.js.

Romoval of those parameters will have any impacts??

Im getting the below excpetion:
04-27 10:40:39.648: W/System.err(2040): java.io.FileNotFoundException: null/com.ionicframework.xxx/Cache/com.Purvotara.purvagraha.png: open failed: ENOENT (No such file or directory)
04-27 10:40:39.648: W/System.err(2040): 	at libcore.io.IoBridge.open(IoBridge.java:456)
04-27 10:40:39.648: W/System.err(2040): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
04-27 10:40:39.648: W/System.err(2040): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
04-27 10:40:39.648: W/System.err(2040): 	at org.jmrezayi2.Applist.Applist.drawableTofile(Applist.java:39)
04-27 10:40:39.648: W/System.err(2040): 	at org.jmrezayi2.Applist.Applist$1.run(Applist.java:121)
04-27 10:40:39.648: W/System.err(2040): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-27 10:40:39.648: W/System.err(2040): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-27 10:40:39.659: W/System.err(2040): 	at java.lang.Thread.run(Thread.java:818)
04-27 10:40:39.659: W/System.err(2040): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-27 10:40:39.659: W/System.err(2040): 	at libcore.io.Posix.open(Native Method)
04-27 10:40:39.659: W/System.err(2040): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-27 10:40:39.659: W/System.err(2040): 	at libcore.io.IoBridge.open(IoBridge.java:442)
04-27 10:40:39.659: W/System.err(2040): 	... 7 more
04-27 10:40:39.668: W/System.err(2040): java.io.FileNotFoundException: null/com.ionicframework.xxx/Cache/com.purvotara.moinga.png: open failed: ENOENT (No such file or directory)
04-27 10:40:39.668: W/System.err(2040): 	at libcore.io.IoBridge.open(IoBridge.java:456)
04-27 10:40:39.668: W/System.err(2040): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
04-27 10:40:39.668: W/System.err(2040): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
04-27 10:40:39.668: W/System.err(2040): 	at org.jmrezayi2.Applist.Applist.drawableTofile(Applist.java:39)
04-27 10:40:39.668: W/System.err(2040): 	at org.jmrezayi2.Applist.Applist$1.run(Applist.java:121)
04-27 10:40:39.668: W/System.err(2040): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-27 10:40:39.668: W/System.err(2040): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-27 10:40:39.668: W/System.err(2040): 	at java.lang.Thread.run(Thread.java:818)
04-27 10:40:39.668: W/System.err(2040): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-27 10:40:39.687: W/System.err(2040): 	at libcore.io.Posix.open(Native Method)
04-27 10:40:39.687: W/System.err(2040): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-27 10:40:39.687: W/System.err(2040): 	at libcore.io.IoBridge.open(IoBridge.java:442)
04-27 10:40:39.687: W/System.err(2040): 	... 7 more

The exception says that file not found for storing the images. Should i need to create any folder? Please shed some lights. I'm stucked up in an Lions den. 

Im attaching the image as well. 
![screen shot 2015-04-27 at 10 40 48 am](https://cloud.githubusercontent.com/assets/7545011/7342011/4e523fa0-ecca-11e4-924f-c13820264efd.png)

**Comment by jmrezayi2** [comment]
Hello,

I am happy you see this plugin useful. 
Removal of those has no impact and those wre redundant. Could you help me to update the readme to remove the parts which were not updated?

the recent error you are getting is basically coming from:
null/com.ionicframework.xxx/Cache/com.Purvotara.purvagraha.png:

The part that seems like a flag to me is the "null" at the beginning. Does your device has sd memory, or at least a virtual one?
The plugin tries to store the image in sdcard with path "/com.ionicframework.xxx/Cache/com.Purvotara.purvagraha.png" but apparently it can not find the root sd card for your phone.

**Comment by jmrezayi2** [comment]
Do you have file plugin in your app? the plugin is trying to save icons in a folder, so your app must have access to the sdcard, or the storage of the device..

**Comment by Sharathnasa** [comment]
Hello,
Good to hear that removal of those parameters has no affect. Thank you. You want me to remove those parameter from .js and update the Readme file? If you want sure, i will do that. No problem.

Regarding the error. I was running it on the emulator, which might don't have memory and also i haven't added the permission to access sd card. I will add the permission and let you know.

One more thing, i wanted to take only package name as another record in the output json. I need to change the code in java file i think. Could you please shed some light on the same?

Regards,
SharathNasa

**Comment by Sharathnasa** [comment]
Hello,

I was able to get only package name which i was talking about in the above message. Just added few lines of code in java file that's it.

And one thing i wanted to check with you. Does you plugin also lists system apps?.....

If not could you please update the plugin to include the system app as well or please shed some lights to me.

Regards,
SharathNasa

**Comment by jmrezayi2** [comment]
I am happy you were able to make it work!

well to have the system apps, just go to the java file of this plugin (Applist.java) and change line 99. Just google on how to get the list of apps including system apps..

**Comment by Sharathnasa** [comment]
Hello,

I tired to change the plugin to get all installed app, including system app, but no luck. Could you help me to do the same. 

Regards,
Sharath

**Comment by jmrezayi2** [comment]
Hi!

Can you tell me which line did you change? 

Thanks,

**Comment by jmrezayi2** [comment]
You just need to remove the if on line 8 of the java file.

**Comment by CjoyHome** [comment]
ionic3 Is it correct to use this?`(<any>window).Applist.createEvent('', '', '', '', '', (app_list)=>{
      alert(JSON.stringify(app_list));
      console.log(JSON.stringify(app_list));
    }, (app_list)=>{
      alert("Oopsie! " + app_list);
      console.log("Oopsie! " + app_list);
    });`

**Comment by CjoyHome** [comment]
I want to get a list of applications that have been installed on the phone
