### ISSUE TITLE
getTime Error

### ISSUE THREAD

**Issue by 10ur10der** [jmrezayi2/Applist#6]
TypeError: Object  has no method 'getTime'  I get an error. What would be the reason?

**Comment by anup5708** [comment]
I am also facing the same issue...
![capture](https://cloud.githubusercontent.com/assets/8477671/23258796/d1631fac-f9ef-11e6-9b95-7a3cf920de39.JPG)

**Comment by 10ur10der** [comment]
I solved the problem.Open the file where the project is located.In the folder search for Applist.js.There must be four applist.js files.Open them in notepad ++ and make changes in all.I work for me.I hope it works for you.Or have different plugins try them [https://github.com/KIvanow/installedApps](url)
               `"startTimeMillis": startDate.getTime(),
                "endTimeMillis": endDate.getTime()`
               
                ` "startTimeMillis": ""//, startDate.getTime(),
                  "endTimeMillis": ""// endDate.getTime()`

**Comment by jmrezayi2** [comment]
Hello 10ur10der and anup5708,

Thanks for opening the issue, I just removed the functions and made a new commit. It should work fine now!
